name: build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
    branches-ignore:
      - daily
    tags:
      - '*'
jobs:
  build-apple:
    runs-on: macOS-11.0
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.ios-release.tar.gz
          path: lib/ios/release/webrtc.tar.gz
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.linux-debug.tar.gz
          path: lib/linux/debug/webrtc.tar.gz
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.android-release.tar.gz
          path: lib/android/release/webrtc.tar.gz
  create-release:
    name: Create Release
    needs: [build-android, build-apple, build-linux]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Tree Artifacts
        run: tree .
      - name: ls Artifacts
        run: ls -la
      - name: filetype
        run: file webrtc.ios-release.tar.gz