name: build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
    branches-ignore:
      - daily
    tags:
      - '*'
jobs:
  build-apple:
    runs-on: macOS-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.ios-release.tar.gz
          path: lib/ios/release/webrtc.tar.gz
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.linux-debug.tar.gz
          path: lib/linux/debug/webrtc.tar.gz
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build WebRTC
        run: echo "*Fake Building*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.android-release.tar.gz
          path: lib/android/release/webrtc.tar.gz
#  create-release:
#    name: Create Release
#    if: contains(github.ref, 'tags/m')
#    needs: [build-windows, build-apple, build-linux]
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1.0.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
#      - name: Output upload url
#        shell: bash
#        run: echo "UPLOAD_URL='${{ steps.create_release.outputs.upload_url }}'" > create-release.env
#      - name: Upload create-release Environment
#        uses: actions/upload-artifact@v1
#        with:
#          name: create-release.env
#          path: create-release.env